name: pec-erp
services:
  postgres:
    image: postgres:16-alpine
    container_name: pec_postgres
    restart: always
    environment:
      POSTGRES_DB: "pec"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: PECApp-Backend
    restart: always
    ports:
      - "4000:4000"
      - "50051:50051"
    environment:
      JWT_SECRET: "pec_secret_key_2026"
      PORT: "4000"
      NODE_ENV: "development"
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/pec"
    command: >
      sh -c " cd /app/packages/database && npx prisma db push --accept-data-loss && cd /app/apps/server && node -r tsconfig-paths/register dist/apps/server/src/main.js "
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/api"]
      interval: 10s
      timeout: 5s
      retries: 5

  envoy:
    image: envoyproxy/envoy:v1.27-latest
    container_name: pec_envoy
    ports:
      - "8080:8080"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: pec_redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pec_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"



  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: PECApp-Frontend
    restart: always
    ports:
      - "3000:3001" # Host listens on 3000, forwards to container's 3001
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:4000/api"
      INTERNAL_API_URL: "http://backend:4000/api"
    depends_on:
      - backend

  dev_seed:
    image: node:20-alpine
    container_name: pec_dev_seed
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/pec"
    depends_on:
      - postgres
    command: sh -c "npm install --legacy-peer-deps && npx ts-node apps/server/seed.ts"

  dev_worker:
    image: node:20-alpine
    container_name: pec_dev_worker
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      REDIS_URL: "redis://redis:6379"
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/pec"
    depends_on:
      - redis
      - postgres
    command: sh -c "npm install --legacy-peer-deps && npx ts-node apps/server/src/background-jobs/worker.ts"

volumes:
  postgres_data:
