services:
  postgres:
    image: postgres:16-alpine
    container_name: pec_postgres
    restart: always
    environment:
      POSTGRES_DB: "pec"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: pec_backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      JWT_SECRET: "pec_secret_key_2026"
      PORT: "4000"
      NODE_ENV: "development"
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/pec"
    command: >
      sh -c " npx prisma db push --accept-data-loss && npm run db:seed && npm run start:dev "
    depends_on:
      - postgres

volumes:
  postgres_data:
