# syntax=docker/dockerfile:1.4
FROM node:26-bookworm-slim

# Pre-install openssl and other essential dev utilities so we don't have to apt-get them at runtime
RUN apt-get update -y && \
    apt-get install -y openssl git curl ca-certificates gnupg lsb-release && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    chmod a+r /etc/apt/keyrings/docker.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update -y && \
    apt-get install -y docker-ce-cli && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Enable pnpm
RUN corepack enable pnpm

WORKDIR /app

# We will rely on volumes to mount code.

# We'll override CMD in docker-compose.dev.yml
CMD ["node"]
