# syntax=docker/dockerfile:1.4
FROM node:22-bookworm-slim

# Pre-install openssl and other essential dev utilities so we don't have to apt-get them at runtime
RUN apt-get update -y && \
    apt-get install -y openssl git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Enable pnpm
RUN corepack enable pnpm

WORKDIR /app

# We will rely on volumes to mount code.

# We'll override CMD in docker-compose.dev.yml
CMD ["node"]
