import { z } from 'zod';
export declare const departmentSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodString;
    code: z.ZodString;
    hod: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    name: string;
    code: string;
    id?: string | undefined;
    description?: string | undefined;
    hod?: string | undefined;
}, {
    name: string;
    code: string;
    id?: string | undefined;
    description?: string | undefined;
    hod?: string | undefined;
}>;
export declare const facultySchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    fullName: z.ZodString;
    email: z.ZodString;
    department: z.ZodString;
    employeeId: z.ZodString;
    designation: z.ZodString;
    specialization: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    email: string;
    department: string;
    employeeId: string;
    designation: string;
    fullName: string;
    id?: string | undefined;
    phone?: string | undefined;
    specialization?: string | undefined;
}, {
    email: string;
    department: string;
    employeeId: string;
    designation: string;
    fullName: string;
    id?: string | undefined;
    phone?: string | undefined;
    specialization?: string | undefined;
}>;
export declare const attendanceSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    studentId: z.ZodString;
    subject: z.ZodString;
    date: z.ZodString;
    status: z.ZodEnum<["present", "absent", "late"]>;
    remarks: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    studentId: string;
    status: "absent" | "late" | "present";
    date: string;
    subject: string;
    id?: string | undefined;
    remarks?: string | undefined;
}, {
    studentId: string;
    status: "absent" | "late" | "present";
    date: string;
    subject: string;
    id?: string | undefined;
    remarks?: string | undefined;
}>;
export declare const courseSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodString;
    code: z.ZodString;
    department: z.ZodString;
    credits: z.ZodDefault<z.ZodNumber>;
    instructorId: z.ZodOptional<z.ZodString>;
    instructor: z.ZodOptional<z.ZodString>;
    semester: z.ZodOptional<z.ZodNumber>;
    status: z.ZodDefault<z.ZodEnum<["active", "inactive", "archived"]>>;
}, "strip", z.ZodTypeAny, {
    name: string;
    status: "active" | "inactive" | "archived";
    department: string;
    code: string;
    credits: number;
    id?: string | undefined;
    semester?: number | undefined;
    instructor?: string | undefined;
    instructorId?: string | undefined;
}, {
    name: string;
    department: string;
    code: string;
    id?: string | undefined;
    semester?: number | undefined;
    status?: "active" | "inactive" | "archived" | undefined;
    credits?: number | undefined;
    instructor?: string | undefined;
    instructorId?: string | undefined;
}>;
export declare const userSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    fullName: z.ZodString;
    email: z.ZodString;
    role: z.ZodDefault<z.ZodEnum<["student", "faculty", "college_admin", "super_admin"]>>;
    status: z.ZodDefault<z.ZodEnum<["active", "inactive", "suspended"]>>;
    department: z.ZodOptional<z.ZodString>;
    enrollmentNumber: z.ZodOptional<z.ZodString>;
    semester: z.ZodOptional<z.ZodNumber>;
    employeeId: z.ZodOptional<z.ZodString>;
    designation: z.ZodOptional<z.ZodString>;
    specialization: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    email: string;
    role: "college_admin" | "faculty" | "student" | "super_admin";
    status: "active" | "suspended" | "inactive";
    fullName: string;
    id?: string | undefined;
    semester?: number | undefined;
    department?: string | undefined;
    employeeId?: string | undefined;
    designation?: string | undefined;
    phone?: string | undefined;
    specialization?: string | undefined;
    enrollmentNumber?: string | undefined;
}, {
    email: string;
    fullName: string;
    id?: string | undefined;
    role?: "college_admin" | "faculty" | "student" | "super_admin" | undefined;
    semester?: number | undefined;
    status?: "active" | "suspended" | "inactive" | undefined;
    department?: string | undefined;
    employeeId?: string | undefined;
    designation?: string | undefined;
    phone?: string | undefined;
    specialization?: string | undefined;
    enrollmentNumber?: string | undefined;
}>;
export declare const enrollmentSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    studentId: z.ZodString;
    courseId: z.ZodString;
    courseName: z.ZodString;
    courseCode: z.ZodString;
    semester: z.ZodOptional<z.ZodNumber>;
    batch: z.ZodOptional<z.ZodString>;
    status: z.ZodDefault<z.ZodEnum<["active", "inactive", "completed", "withdrawn"]>>;
    enrolledAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    studentId: string;
    courseId: string;
    courseName: string;
    courseCode: string;
    status: "active" | "inactive" | "completed" | "withdrawn";
    id?: string | undefined;
    semester?: number | undefined;
    batch?: string | undefined;
    enrolledAt?: string | undefined;
}, {
    studentId: string;
    courseId: string;
    courseName: string;
    courseCode: string;
    id?: string | undefined;
    semester?: number | undefined;
    batch?: string | undefined;
    status?: "active" | "inactive" | "completed" | "withdrawn" | undefined;
    enrolledAt?: string | undefined;
}>;
export declare const hostelIssueSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    title: z.ZodString;
    description: z.ZodString;
    category: z.ZodString;
    priority: z.ZodEnum<["low", "medium", "high", "emergency"]>;
    status: z.ZodDefault<z.ZodEnum<["pending", "assigned", "resolved", "closed"]>>;
    roomNumber: z.ZodString;
    studentId: z.ZodString;
    studentName: z.ZodString;
    organizationId: z.ZodOptional<z.ZodString>;
    responses: z.ZodOptional<z.ZodUnknown>;
    createdAt: z.ZodOptional<z.ZodString>;
    updatedAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    studentId: string;
    status: "pending" | "assigned" | "resolved" | "closed";
    description: string;
    category: string;
    studentName: string;
    title: string;
    priority: "medium" | "high" | "low" | "emergency";
    roomNumber: string;
    id?: string | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    organizationId?: string | undefined;
    responses?: unknown;
}, {
    studentId: string;
    description: string;
    category: string;
    studentName: string;
    title: string;
    priority: "medium" | "high" | "low" | "emergency";
    roomNumber: string;
    id?: string | undefined;
    status?: "pending" | "assigned" | "resolved" | "closed" | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    organizationId?: string | undefined;
    responses?: unknown;
}>;
export declare const timetableSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    courseId: z.ZodOptional<z.ZodString>;
    courseName: z.ZodString;
    courseCode: z.ZodString;
    facultyId: z.ZodOptional<z.ZodString>;
    facultyName: z.ZodOptional<z.ZodString>;
    day: z.ZodEnum<["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]>;
    startTime: z.ZodString;
    endTime: z.ZodString;
    room: z.ZodString;
    department: z.ZodOptional<z.ZodString>;
    semester: z.ZodOptional<z.ZodNumber>;
    batch: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    courseName: string;
    courseCode: string;
    day: "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday";
    startTime: string;
    endTime: string;
    room: string;
    id?: string | undefined;
    courseId?: string | undefined;
    semester?: number | undefined;
    batch?: string | undefined;
    facultyId?: string | undefined;
    facultyName?: string | undefined;
    department?: string | undefined;
}, {
    courseName: string;
    courseCode: string;
    day: "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday";
    startTime: string;
    endTime: string;
    room: string;
    id?: string | undefined;
    courseId?: string | undefined;
    semester?: number | undefined;
    batch?: string | undefined;
    facultyId?: string | undefined;
    facultyName?: string | undefined;
    department?: string | undefined;
}>;
export declare const examinationSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    courseId: z.ZodString;
    examType: z.ZodEnum<["midterm", "final", "quiz", "lab"]>;
    date: z.ZodString;
    startTime: z.ZodString;
    endTime: z.ZodString;
    room: z.ZodString;
}, "strip", z.ZodTypeAny, {
    courseId: string;
    startTime: string;
    endTime: string;
    room: string;
    date: string;
    examType: "midterm" | "final" | "quiz" | "lab";
    id?: string | undefined;
}, {
    courseId: string;
    startTime: string;
    endTime: string;
    room: string;
    date: string;
    examType: "midterm" | "final" | "quiz" | "lab";
    id?: string | undefined;
}>;
export type DepartmentInput = z.infer<typeof departmentSchema>;
export type FacultyInput = z.infer<typeof facultySchema>;
export type AttendanceInput = z.infer<typeof attendanceSchema>;
export type CourseInput = z.infer<typeof courseSchema>;
export type UserInput = z.infer<typeof userSchema>;
export type EnrollmentInput = z.infer<typeof enrollmentSchema>;
export type HostelIssueInput = z.infer<typeof hostelIssueSchema>;
export type TimetableInput = z.infer<typeof timetableSchema>;
export type ExaminationInput = z.infer<typeof examinationSchema>;
